"""
开发环境配置
"""

# mysql 相关配置

MYSQL_HOST = "127.0.0.1"
MYSQL_PORT = '3306'
MYSQL_USER_NAME = 'an'
MYSQL_PASSWORD = '123'

SQLALCHEMY_DATABASE_URI = f'mysql://{MYSQL_USER_NAME}:{MYSQL_PASSWORD}@{MYSQL_HOST}/default'
SQLALCHEMY_BINDS = {
    'blog': f'mysql://{MYSQL_USER_NAME}:{MYSQL_PASSWORD}@{MYSQL_HOST}/blogs_db',
}
